apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-deployment
  name: demo-deployment
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-deployment
    spec:
      containers:
      - image: bash:latest
        command: ["sleep"]
        args: ["600"]
        imagePullPolicy: IfNotPresent
        name: demo-deployment
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: DEMO_SECRET
            valueFrom:
              secretKeyRef:
                name: demo-secret
                key: demo-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
