apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-service
  name: secret-service
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
      - image: secret-service:latest
        imagePullPolicy: Never
        name: secret-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: secret-service
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
