apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-service
  namespace: development
subjects:
- kind: ServiceAccount
  name: secret-service
  namespace: development
  apiGroup: ""
roleRef:
  kind: Role
  name: secret-service
  apiGroup: ""