apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-service
  namespace: development
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch